name: Refresh Answer Key and Solution from Jnanasudha.com (JEE & KCET)

on:
  push:
    paths:
      - "fix_json.py"

permissions:
  contents: write

jobs:
  fix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Run fix_json.py
        run: python fix_json.py

      - name: Commit changes
        run: |
          git config user.name "prathambhandary"
          git config user.email "pratham@firewave.in"
          git add -A
          if git diff --staged --quiet; then
            echo "No changes."
          lse
            git commit -m "Deleting old JEE & KCET JUT Answer Key"
            git push origin main
          fi  

      - name: Trigger scraper
        env:
          GH_TOKEN: ${{ secrets.PUSHKITTY_TOKEN }}
        run: gh workflow run "Auto Scrape Questions from Jnanasudha.com (JEE & KCET)" --ref main